service: serverless-guru-challenge

custom:
  tableName: 'blogs-table-${sls:stage}'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
  environment:
    POSTS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    BlogsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
