service: serverless-guru-challenge
frameworkVersion: '3'

custom:
  tableName: 'blogs-table-${sls:stage}'

provider:
  name: aws
  role: arn:aws:iam::517822307334:role/serverless_guru_role
  runtime: nodejs16.x
  region: us-west-1
  environment:
    BLOGS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    BlogsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
